version: '2'

########################################################################################################################
# NETWORKS
########################################################################################################################
#networks:
#
#  repo-net:
#    external:
#      name: repo-net

########################################################################################################################
# VOLUMES
########################################################################################################################
#volumes:
#
#  nexus-data:

########################################################################################################################
# SERVICES
########################################################################################################################
services:

  nginx:
    container_name: nginx
    image: "nginx"
    ports:
      - "443:443"
      - "80:80"
#    volumes:
#      - ./files/conf.d:/etc/nginx/conf.d
#      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
#    networks:
#      - repo-net
#    restart: always

#  nexus:
#    container_name: nexus
#    ports:
#      - 8081:8081
#      - 127.0.0.1:5000:5000
#    build:
#      context: nexus/.
#      args:
#        - http_proxy
#        - https_proxy
##    environment:
##      - VIRTUAL_HOST=nexus.npd.learndirect.com
#    volumes:
#      - nexus-data:/nexus-data
#    networks:
#      - repo-net
#    restart: always
